{"cause":{"code":"ENOTFOUND","errno":-3008,"hostname":"cluster0-shard-00-01.dgoei.mongodb.net","syscall":"getaddrinfo"},"connectionGeneration":0,"level":"error","message":"failed to connect database getaddrinfo ENOTFOUND cluster0-shard-00-01.dgoei.mongodb.net","stack":"MongoNetworkError: getaddrinfo ENOTFOUND cluster0-shard-00-01.dgoei.mongodb.net\n    at connectionFailureError (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\mongodb\\src\\cmap\\connect.ts:491:14)\n    at TLSSocket.<anonymous> (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\mongodb\\src\\cmap\\connect.ts:392:16)\n    at Object.onceWrapper (node:events:629:26)\n    at TLSSocket.emit (node:events:514:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"failed to connect database Socket already opened","stack":"Error: Socket already opened\n    at RedisSocket.connect (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\@redis\\client\\dist\\lib\\client\\socket.js:48:19)\n    at Commander.connect (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:184:71)\n    at D:\\web-2\\api-gateway-redis\\university-management-authService\\src\\shared\\redis.ts:14:26\n    at Generator.next (<anonymous>)\n    at fulfilled (D:\\web-2\\api-gateway-redis\\university-management-authService\\src\\shared\\redis.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"failed to connect database Socket already opened","stack":"Error: Socket already opened\n    at RedisSocket.connect (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\@redis\\client\\dist\\lib\\client\\socket.js:48:19)\n    at Commander.connect (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:184:71)\n    at D:\\web-2\\api-gateway-redis\\university-management-authService\\src\\shared\\redis.ts:14:26\n    at Generator.next (<anonymous>)\n    at fulfilled (D:\\web-2\\api-gateway-redis\\university-management-authService\\src\\shared\\redis.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"failed to connect database Socket already opened","stack":"Error: Socket already opened\n    at RedisSocket.connect (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\@redis\\client\\dist\\lib\\client\\socket.js:48:19)\n    at Commander.connect (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:184:71)\n    at D:\\web-2\\api-gateway-redis\\university-management-authService\\src\\shared\\redis.ts:14:26\n    at Generator.next (<anonymous>)\n    at fulfilled (D:\\web-2\\api-gateway-redis\\university-management-authService\\src\\shared\\redis.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"failed to connect database Socket already opened","stack":"Error: Socket already opened\n    at RedisSocket.connect (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\@redis\\client\\dist\\lib\\client\\socket.js:48:19)\n    at Commander.connect (D:\\web-2\\api-gateway-redis\\university-management-authService\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:184:71)\n    at D:\\web-2\\api-gateway-redis\\university-management-authService\\src\\shared\\redis.ts:14:26\n    at Generator.next (<anonymous>)\n    at fulfilled (D:\\web-2\\api-gateway-redis\\university-management-authService\\src\\shared\\redis.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
